/** Major cities of Pakistan for location selects */
export const PAKISTAN_CITIES = [
  "Abbottabad",
  "Attock",
  "Bahawalpur",
  "Bannu",
  "Chiniot",
  "Dera Ghazi Khan",
  "Dera Ismail Khan",
  "Faisalabad",
  "Gilgit",
  "Gujranwala",
  "Gujrat",
  "Gwadar",
  "Hyderabad",
  "Islamabad",
  "Jacobabad",
  "Jhelum",
  "Karachi",
  "Kasur",
  "Kohat",
  "Lahore",
  "Larkana",
  "Mardan",
  "Mingora",
  "Mirpur",
  "Multan",
  "Muzaffarabad",
  "Muzaffargarh",
  "Nawabshah",
  "Okara",
  "Peshawar",
  "Quetta",
  "Rahim Yar Khan",
  "Rawalpindi",
  "Sahiwal",
  "Sargodha",
  "Sheikhupura",
  "Sialkot",
  "Sukkur",
  "Turbat",
].sort((a, b) => a.localeCompare(b));
