-- AlterTable
ALTER TABLE "Match" ADD COLUMN "scoreJson" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "Match" ADD COLUMN "scoreLogJson" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Match" ADD COLUMN "winnerTeam" INTEGER;
ALTER TABLE "Match" ADD COLUMN "rewardsApplied" BOOLEAN NOT NULL DEFAULT 0;
